//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDWorkersManager._4InfrastructureData.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movements
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Datetime { get; set; }
        public int BankAccountId { get; set; }
    
        public virtual BankAccounts BankAccounts { get; set; }
    }
}
